# Generated by Django 4.2 on 2023-05-02 13:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_vendor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Описание товара', null=True, verbose_name='text'),
        ),
    ]
