"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2se0(q)puqbjjflh56lujzq1rm_3&mq=5)a%6b_5hs2+oaa2!j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'userauth',
    'ckeditor',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'userauth.context_processors.register_view',
                'store.context_processors.categories',
                'store.context_processors.cat_related_products',
                'store.context_processors.brands',
                'store.context_processors.adress',
               
               

        
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL ='static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'


# JAZZMIN_SETTINGS = [
#     'site_header': 'Ecomerce Shop',
#     'site_brand': 'Ваши заказы',
#     'site_logo': 'static/assets/shop_logo.png',

# ]



AUTH_USER_MODEL = 'userauth.User'

CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_CONFIGS = {
    "default": {
        "skin": "moono",
        "codeSnippet_theme": "momokai",
        "toolbar": 'all',
        "extraPlugins": ','.join(
        [
            "codesnippet",
            "widget",
            "dialog",
        ]
        ),
    }
}


# CKEDITOR_CONFIGS = {
#          # Когда имя конфигурации по умолчанию, django-ckeditor использует эту конфигурацию по умолчанию
#     'default': {
#                  # Используйте упрощенный китайский
#         'language':'zh-cn',
#                  # Пожалуйста, установите ширину и высоту редактора в соответствии с вашей страницей
#         'width':'730px',
#         'height':'150px',
#         'image_previewText':' ',
#         'tabSpaces': 4,
#         'toolbar': 'Custom',
#                  # Добавить кнопку здесь
#         'toolbar_Custom': [
#             ['Bold', 'Italic', 'Underline', 'Format', 'RemoveFormat'],
#             ['NumberedList', 'BulletedList'],
#             ['Blockquote', 'CodeSnippet'],
#             ['Image', 'Link', 'Unlink'],
#             ['Maximize']
#         ],
#                  # Плагин
#         'extraPlugins': ','.join(['codesnippet','uploadimage','widget','lineutils',]),
#     }
# }